[package]
name = "star"
version = "0.1.0"
edition = "2021"

[dependencies]
oqs = "*"
aes = "*"
hkdf = "*"
rand = "*"
sha2 = "*"
sha3 = "*"
anyhow = "*"
bincode = "*"
serde = { version = "^1.0.210", features = ["derive"] }
ctr = "*"
generic-array = "*"